name: deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t jwhitedev/chia-web:latest -f Dockerfile.dev .

      - name: Push Docker image to DockerHub
        run: docker push jwhitedev/chia-web:latest

      - name: Copy file to remote server
        run: scp -i ${{ secrets.REMOTE_USER_SSH_KEY }} compose.prod.yaml ${{ secrets.REMOTE_USERNAME }}@${{ secrets.REMOTE_HOST }}:/srv

      - name: SSH into remote server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USERNAME }}
          key: ${{ secrets.REMOTE_USER_SSH_KEY }}
          script: |
            touch success
          #   add command that transfers the docker-compose.prod.yaml file from the root of the repo to an app directory on the remote server
